### ISSUE TITLE
Grammar definition needs to upgraded

### ISSUE THREAD

**Issue by jonpchin** [mafait/Thinknowlogy#1]
Only spent about 2 minutes playing with the application but if it can't handle basic sentences with a few words what is the point?

2784,Expert> who am i
! I don't understand this sentence. Please make sure to enter a sentence conform my limited grammar definition.
! 
2784,Expert> Jon is a boy
2785,Expert> Jon is 22
! I don't understand this sentence. Please make sure to enter a sentence conform my limited grammar definition.
! 
2785,Expert> Jon is 22 years old
! I don't understand this sentence. Please make sure to enter a sentence conform my limited grammar definition.
! 
2785,Expert> Jon is twenty years old.
! I don't understand this sentence. Please make sure to enter a sentence conform my limited grammar definition.
! 
2785,Expert> Jon is 22 years old.
! I don't understand this sentence. Please make sure to enter a sentence conform my limited grammar definition.
! 
2785,Expert> who is jon?
! I don't understand this sentence. Please make sure to enter a sentence conform my limited grammar definition.
!

**Comment by mafait** [comment]
Jonathan, my software isn't a chatbot.

My software is the world's only natural language reasoner. But it has a limited grammar. You must have used the "Login as Expert" button. But clearly, you haven't read my documentation yet.

I suggest to read the documentation first. And if you don't like the limited grammar, I suggest to use any chatbot instead of my natural language reasoner. Because chatbots accept all input. But they unable to reason logically. Moreover, chatbots are only able to select a human-written sentence, in which they may fill-in user-written keywords.

**Comment by mafait** [comment]
Jonathan, my software isn't a chatbot.

My software is the world's only natural language reasoner. But it has a limited grammar. You must have used the "Login as Expert" button. But clearly, you haven't read my documentation yet.

I suggest to read the documentation first. And if you don't like the limited grammar, I suggest to use any chatbot instead of my natural language reasoner. Because chatbots accept all input. But they are unable to reason logically. Moreover, chatbots are only able to select a human-written sentence, in which they may fill-in user-written keywords.
